FROM quay.io/keycloak/keycloak:24.0.3 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=<DBVENDOR>

WORKDIR /opt/keycloak

# add custom theme to providers folder before build step
# COPY ./themes/ providers/

# build server.p12 from private & crt using this command: openssl pkcs12 -export -in PUBLIC_CERT.crt -inkey PRIVATE_KEY.key -certfile PUBLIC_CERT.crt -out server.p12 -name server
COPY certs/server.p12 conf/server.p12

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:24.0.3
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_DB_URL=<DBURL>
ENV KC_DB_USERNAME=<DBUSERNAME>
ENV KC_DB_PASSWORD=<DBPASSWORD>

# environments of keyStore file
ENV KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/server.p12
ENV KC_HTTPS_KEY_STORE_TYPE=PKCS12

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
